CREATE DATABASE IF NOT EXISTS ai_voice;

USE ai_voice;

CREATE TABLE IF NOT EXISTS conversation_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  call_sid VARCHAR(64),
  role VARCHAR(20),
  message TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
