version: '3.8'

services:
  twilio_api:
    image: python:3.11
    container_name: twilio_api
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - twilio_call_log
    command: >
      sh -c "pip install -r /app/requirements.txt && python app.py"
    restart: always

  twilio_call_log:
    image: mysql:8
    container_name: twilio_call_log
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ai_voice
      MYSQL_USER: voiceuser
      MYSQL_PASSWORD: voicepass
    ports:
      - "3306:3306"
    volumes:
      - twilio_call_log_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d  # ✅ run all .sql scripts on first start
    restart: always

volumes:
  twilio_call_log_data: